// Auto-generated from 'ccrcc ... 2026 ХУДАЛДАН АВАХ АЖИЛЛАГААНЫ ТӨЛӨВЛӨГӨӨ.xlsx' (sheet PP-2026).
// Seeded into the procurement_plans table on first run when the table is empty.
export interface ProcurementSeedRow {
  idx: number | null;
  code: string;
  name: string;
  type: string;
  budgetCost: number;
  yearFinancing: number;
  tenderMethod: string;
  tenderMonth: string;
  sustainable: string;
  notes: string;
  projectName: string;
  implementPeriod: string;
  committeeFormed: string;
  advertised: string;
  tenderOpened: string;
  committeeMet: string;
  noticeSent: string;
  contractSigned: string;
  contractValue: number;
  payment1: number;
  payment2: number;
  payment3: number;
  variance: string;
  extraNotes: string;
}

export const procurementSeed: ProcurementSeedRow[] = [
  {
    "idx": 1,
    "code": "УАӨСХАТТӨААТҮГ/1/202601",
    "name": "Парисын хэлэлцээрийн 4-р зүйлд заасны дагуу “Үндэсний хэмжээнд тодорхойлсон хувь нэмэр”-ийн хэрэгжилтийн талаарх мэдээлэл болон Үндэсний тайлан илтгэлийн бичвэр бэлтгэх үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 98686,
    "yearFinancing": 98686,
    "tenderMethod": "Харьцуулалтын арга",
    "tenderMonth": "VI, VII сар",
    "sustainable": "үгүй",
    "notes": "Тендер шалгаруулалтаар худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "10-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "98,686.00",
    "extraNotes": ""
  },
  {
    "idx": 2,
    "code": "УАӨСХАТТӨААТҮГ/1/202602",
    "name": "Нүүрстөрөгчийн нөөцийг хянах төхөөрөмж худалдан авах",
    "type": "бараа",
    "budgetCost": 70000,
    "yearFinancing": 70000,
    "tenderMethod": "Харьцуулалтын арга",
    "tenderMonth": "Судалгаа явуулах",
    "sustainable": "үгүй",
    "notes": "Тендер шалгаруулалтаар худалдан авалт хийнэ",
    "projectName": "Peatland",
    "implementPeriod": "",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 3,
    "code": "УАӨСХАТТӨААТҮГ/1/202603",
    "name": "Ажлын хэсэг, техникийн баг болон мэдээлэл нийлүүлэгч талуудтай уулзалт, хэлэлцүүлгийн зөвлөлдөх уулзалтуудыг зохион байгуулах үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19250,
    "yearFinancing": 19250,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "IX сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 4,
    "code": "УАӨСХАТТӨААТҮГ/1/202604",
    "name": "Ногоон таксономи болон татварын бенчмаркингийн тайлангийн хүрээнд сургалт, хэлэлцүүлэг зохион байгуулах үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19500,
    "yearFinancing": 19500,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "IX, X сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "ADPC",
    "implementPeriod": "",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 5,
    "code": "УАӨСХАТТӨААТҮГ/1/202605",
    "name": "Арга зүй болон салбар дамнасан элементүүдийн хэлэлцүүлэг зохион байгуулахад шаардлагатай бараа материал худалдах авах",
    "type": "үйлчилгээ",
    "budgetCost": 4025,
    "yearFinancing": 4025,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "IX сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 6,
    "code": "УАӨСХАТТӨААТҮГ/1/202606",
    "name": "Ирээдүйд шаардлагатай санхүүгийн дэмжлэг, технологийн хөгжүүлэлт ба шилжилт, мөн чадавхыг бэхжүүлэх дэмжлэгтэй холбоотой мэдээлэл бэлтгэх зөвлөх үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19500,
    "yearFinancing": 19500,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VII сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "10-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 7,
    "code": "УАӨСХАТТӨААТҮГ/1/202607",
    "name": "Өнгөрсөн хугацаанд хүлээн авсан санхүүгийн дэмжлэг, технологийн хөгжүүлэлт ба шилжилт, мөн чадавх бэхжүүлэх дэмжлэгтэй холбоотой мэдээлэл бэлтгэх зөвлөх үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19500,
    "yearFinancing": 19500,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VII сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "10-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 8,
    "code": "УАӨСХАТТӨААТҮГ/1/202608",
    "name": "Хүний үйл ажиллагаанаас үүдэлтэй хүлэмжийн хийн эх үүсвэрээс ялгарч буй ялгаралт ба шингээгчээс ялгарч буй ялгаралтын үндэсний тооллогын семинар зохион байгуулах /I бүлэг/",
    "type": "үйлчилгээ",
    "budgetCost": 19800,
    "yearFinancing": 19800,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "X сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "10-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 9,
    "code": "УАӨСХАТТӨААТҮГ/1/202609",
    "name": "Хүлэмжийн хийн тооллогын IPPU-ийн салбарын мэдээллээр хангах үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 4462.5,
    "yearFinancing": 4462.5,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VIII сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 10,
    "code": "УАӨСХАТТӨААТҮГ/1/202610",
    "name": "Хүлэмжийн хийн тооллогын эрчим хүчний балансын мэдээллээр хангах үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 4462.5,
    "yearFinancing": 4462.5,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VIII сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 11,
    "code": "УАӨСХАТТӨААТҮГ/1/202611",
    "name": "Үндэсний хэмжээнд тодорхойлсон хувь нэмрийг хэрэгжүүлэх, биелүүлэхэд гарсан ахиц дэвшлийг хянах бүлгийн семинар зохион байгуулах үйлчилгээ /II бүлэг/",
    "type": "үйлчилгээ",
    "budgetCost": 16061.5,
    "yearFinancing": 16061.5,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "X сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "11-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 12,
    "code": "УАӨСХАТТӨААТҮГ/1/202612",
    "name": "Олгож хэрэгжүүлсэн санхүү, технологийн хөгжил, дамжуулалт, чадавхийг бэхжүүлэх дэмжлэгийн талаарх мэдээллийн семинар зохион байгуулах үйлчилгээ /IV бүлэг/",
    "type": "үйлчилгээ",
    "budgetCost": 19250,
    "yearFinancing": 19250,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "X сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "11-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 13,
    "code": "УАӨСХАТТӨААТҮГ/1/202613",
    "name": "Семинаруудын орчуулгын ажил",
    "type": "үйлчилгээ",
    "budgetCost": 19176,
    "yearFinancing": 19176,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VII сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "7-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 14,
    "code": "УАӨСХАТТӨААТҮГ/1/202614",
    "name": "Зөөврийн компьютер /өндөр хурдны/ 1ш",
    "type": "бараа",
    "budgetCost": 9513,
    "yearFinancing": 9513,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "Ерөнхий гэрээний арга",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 15,
    "code": "УАӨСХАТТӨААТҮГ/1/202615",
    "name": "Суурин компьютер 4ш",
    "type": "бараа",
    "budgetCost": 12800,
    "yearFinancing": 12800,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "Шууд хэрэгжих боломжтой",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "5 сард 1ш компьютер худалдан авсан.",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 16,
    "code": "УАӨСХАТТӨААТҮГ/1/202616",
    "name": "Хяналт-шинжилгээ, тайлагналын тогтолцоог ашиглах талаар чадавхыг бэхжүүлэх цуврал сургалтууд зохион байгуулах үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 14000,
    "yearFinancing": 14000,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "IX сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "Peatland",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 17,
    "code": "УАӨСХАТТӨААТҮГ/1/202617",
    "name": "Хүлэрт намгархаг газрын тооллого болон экосистемийн үйлчилгээний үнэлгээний аргачлал боловсруулах үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 69300,
    "yearFinancing": 69300,
    "tenderMethod": "Харьцуулалтын арга",
    "tenderMonth": "VI сар",
    "sustainable": "үгүй",
    "notes": "Тендер шалгаруулалтаар худалдан авалт хийнэ",
    "projectName": "Peatland",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 18,
    "code": "УАӨСХАТТӨААТҮГ/1/202618",
    "name": "Хоёр сав газрын усны тэнцлийн загварт үндэслэн туршилтын дасан зохицох төлөвлөгөөг боловсруулах.",
    "type": "үйлчилгээ",
    "budgetCost": 19250,
    "yearFinancing": 19250,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VI сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "Peatland",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 19,
    "code": "УАӨСХАТТӨААТҮГ/1/202619",
    "name": "Тоног төхөөрөмж: GPS, анхны тусламжийн хэрэгсэл худалдан авах",
    "type": "бараа",
    "budgetCost": 9450,
    "yearFinancing": 9450,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "Судалгаа явуулах",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "Peatland",
    "implementPeriod": "",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 20,
    "code": "УАӨСХАТТӨААТҮГ/1/202620",
    "name": "Туршилтын үйл ажиллагааг хянах төхөөрөмж худалдан авах",
    "type": "бараа",
    "budgetCost": 122500,
    "yearFinancing": 122500,
    "tenderMethod": "Нээлттэй тендер шалгаруулалт",
    "tenderMonth": "Судалгаа явуулах",
    "sustainable": "үгүй",
    "notes": "Тендер шалгаруулалтаар худалдан авалт хийнэ",
    "projectName": "Peatland",
    "implementPeriod": "",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 21,
    "code": "УАӨСХАТТӨААТҮГ/1/202621",
    "name": "Аудит",
    "type": "үйлчилгээ",
    "budgetCost": 7000,
    "yearFinancing": 7000,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VI сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "Peatland",
    "implementPeriod": "6-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 22,
    "code": "УАӨСХАТТӨААТҮГ/1/202622",
    "name": "Цэвэр технологийн инноваци ба бизнесийн экосистем (CIEE)-д судалгаа, дүн шинжилгээ хийж, бусад орны бодлогыг Монгол Улсад нутагшуулж, хэрэгжүүлэх төлөвлөгөө боловсруулах зөвлөх үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19250,
    "yearFinancing": 19250,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VI сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "UNIDO",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 23,
    "code": "УАӨСХАТТӨААТҮГ/1/202623",
    "name": "Монгол Улс дахь технологийн зөрүү болон инновацийн боломжийн талаар хүйсийн мэдрэмжтэй тайлан боловсруулах зөвлөх үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19250,
    "yearFinancing": 19250,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VI сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "UNIDO",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 24,
    "code": "УАӨСХАТТӨААТҮГ/1/202624",
    "name": "Цэвэр технологийн инноваци ба бизнесийн экосистем (CIEE)-г нутагшуулах бодлого, журам, зөвлөмжийн хувилбаруудыг тодорхойлсон тайлан болон хэрэгжилтийн замын зураг боловсруулах зөвлөх үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19250,
    "yearFinancing": 19250,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VI сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "UNIDO",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 25,
    "code": "УАӨСХАТТӨААТҮГ/1/202625",
    "name": "Уур амьсгалын өөрчлөлтөд тэсвэртэй стандарт боловсруулахад дэмжлэг үзүүлэх, сургалт зохион байгуулах үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19500,
    "yearFinancing": 19500,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "IX, X сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "ADPC",
    "implementPeriod": "",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 26,
    "code": "УАӨСХАТТӨААТҮГ/1/202626",
    "name": "Агуулга болон хүлэмжийн хийн үндэсний тооллогод ашиглагдах тоон өгөгдөлд санал авах хэлэлцүүлгийн зохион байгуулах үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 17500,
    "yearFinancing": 17500,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "X сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "10-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 27,
    "code": "УАӨСХАТТӨААТҮГ/1/202627",
    "name": "Үндэсний шинжээчдийн хэлэлцүүлэг хийх  үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 10500,
    "yearFinancing": 10500,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "XI сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "11-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 28,
    "code": "УАӨСХАТТӨААТҮГ/1/202605",
    "name": "Техникийн шинжээчдийн (QA/QC) баталгаажуулах семинар зохион байгуулах үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19250,
    "yearFinancing": 19250,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "XII сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "12-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 29,
    "code": "УАӨСХАТТӨААТҮГ/1/202629",
    "name": "Парисын хэлэлцээрийн 13 дугаар зүйлийн дагуу уур амьсгалын өөрчлөлтийн нөлөөлөл болон дасан зохицох асуудалтай холбоотой мэдээлэл болон Үндэсний тайлан илтгэлийн бичвэр бэлтгэх үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 89051,
    "yearFinancing": 89051,
    "tenderMethod": "Харьцуулалтын арга",
    "tenderMonth": "VI, VII сар",
    "sustainable": "үгүй",
    "notes": "Тендер шалгаруулалтаар худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "10-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 30,
    "code": "УАӨСХАТТӨААТҮГ/1/202630",
    "name": "Парисын хэлэлцээрийн 9-11 дүгээр зүйлүүдийн дагуу хүлээн авсан болон шаардлагатай санхүүгийн дэмжлэг, технологийн хөгжүүлэлт ба шилжилт, мөн чадавх бэхжүүлэх дэмжлэгтэй холбоотой бүлгийн бусад бичвэрийг нэгтгэн бэлтгэх үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19500,
    "yearFinancing": 19500,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "X сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "11-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 31,
    "code": "УАӨСХАТТӨААТҮГ/1/202631",
    "name": "Хүлэмжийн хийн тооллогын AFOLU салбарын мэдээллээр хангах үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 4462.5,
    "yearFinancing": 4462.5,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "X сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "11-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 32,
    "code": "УАӨСХАТТӨААТҮГ/1/202632",
    "name": "Уур амьсгалын өөрчлөлтийн нөлөөлөл болон дасан зохицохтой холбоотой мэдээллийн семинар зохион байгуулах үйлчилгээ /III бүлэг/",
    "type": "үйлчилгээ",
    "budgetCost": 19250,
    "yearFinancing": 19250,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "XI сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "BTR",
    "implementPeriod": "11-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 33,
    "code": "УАӨСХАТТӨААТҮГ/1/202633",
    "name": "Зорилтот сав газарт экосистемийн үйлчилгээний орон зайн тооллого хийх үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 87500,
    "yearFinancing": 87500,
    "tenderMethod": "Харьцуулалтын арга",
    "tenderMonth": "VI сар",
    "sustainable": "үгүй",
    "notes": "Тендер шалгаруулалтаар худалдан авалт хийнэ",
    "projectName": "Peatland",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 34,
    "code": "УАӨСХАТТӨААТҮГ/1/202634",
    "name": "Хоёр сав газарт хүлэрт намгархаг газар болон мөнх цэвдгийн харилцан үйлчлэлд тулгуурласан усны тэнцлийн загварыг тодорхойлох шинжлэх ухааны судалгаа хийх үйлчилгээ",
    "type": "үйлчилгээ",
    "budgetCost": 19250,
    "yearFinancing": 19250,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "VI сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "Peatland",
    "implementPeriod": "9-р сар",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  },
  {
    "idx": 35,
    "code": "УАӨСХАТТӨААТҮГ/1/202635",
    "name": "Оффисын зориулалттай принтер худалдан авах",
    "type": "бараа",
    "budgetCost": 10500,
    "yearFinancing": 10500,
    "tenderMethod": "Шууд худалдан авалт",
    "tenderMonth": "V сар",
    "sustainable": "үгүй",
    "notes": "Тухай бүр захиалгын дагуу худалдан авалт хийнэ",
    "projectName": "Peatland",
    "implementPeriod": "2 принтер худалдан авсан.",
    "committeeFormed": "",
    "advertised": "",
    "tenderOpened": "",
    "committeeMet": "",
    "noticeSent": "",
    "contractSigned": "",
    "contractValue": 0,
    "payment1": 0,
    "payment2": 0,
    "payment3": 0,
    "variance": "",
    "extraNotes": ""
  }
];
